PRAGMA foreign_keys = ON;
CREATE TABLE IF NOT EXISTS tenants (id TEXT PRIMARY KEY, name TEXT NOT NULL, sector TEXT NOT NULL DEFAULT 'Restoran', created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS branches (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL REFERENCES tenants(id), name TEXT NOT NULL, address TEXT NOT NULL DEFAULT '', phone TEXT NOT NULL DEFAULT '', manager TEXT NOT NULL DEFAULT '', tax_no TEXT NOT NULL DEFAULT '', created_at TEXT NOT NULL, UNIQUE(tenant_id,name));
CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL REFERENCES tenants(id), email TEXT NOT NULL UNIQUE, name TEXT NOT NULL, password_hash TEXT NOT NULL, role TEXT NOT NULL, branch_id TEXT REFERENCES branches(id), permissions TEXT NOT NULL DEFAULT '{}', must_change INTEGER NOT NULL DEFAULT 0, active INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS sessions (token_hash TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id), csrf TEXT NOT NULL, expires_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS products (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL REFERENCES tenants(id), name TEXT NOT NULL, category TEXT NOT NULL, price_cents INTEGER NOT NULL CHECK(price_cents>=0), vat_rate INTEGER NOT NULL CHECK(vat_rate BETWEEN 0 AND 100), created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS materials (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL REFERENCES tenants(id), name TEXT NOT NULL, unit TEXT NOT NULL, cost_cents INTEGER CHECK(cost_cents>=0), min_stock REAL NOT NULL DEFAULT 0 CHECK(min_stock>=0), created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS recipes (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL REFERENCES tenants(id), product_id TEXT NOT NULL REFERENCES products(id), material_id TEXT NOT NULL REFERENCES materials(id), quantity REAL NOT NULL CHECK(quantity>0), UNIQUE(product_id,material_id));
CREATE TABLE IF NOT EXISTS inventory (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL REFERENCES tenants(id), branch_id TEXT NOT NULL REFERENCES branches(id), material_id TEXT NOT NULL REFERENCES materials(id), quantity REAL NOT NULL DEFAULT 0 CHECK(quantity>=0), UNIQUE(branch_id,material_id));
CREATE TABLE IF NOT EXISTS moves (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL REFERENCES tenants(id), branch_id TEXT NOT NULL REFERENCES branches(id), material_id TEXT NOT NULL REFERENCES materials(id), kind TEXT NOT NULL, quantity REAL NOT NULL, cost_cents INTEGER, reason TEXT NOT NULL DEFAULT '', date TEXT NOT NULL, ref_id TEXT, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS accounts (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL REFERENCES tenants(id), branch_id TEXT NOT NULL REFERENCES branches(id), name TEXT NOT NULL, type TEXT NOT NULL, opening_cents INTEGER NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS sales (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL REFERENCES tenants(id), branch_id TEXT NOT NULL REFERENCES branches(id), table_id TEXT, channel TEXT NOT NULL, payment TEXT NOT NULL, account_id TEXT REFERENCES accounts(id), total_cents INTEGER NOT NULL CHECK(total_cents>=0), net_cents INTEGER NOT NULL CHECK(net_cents>=0), cost_cents INTEGER CHECK(cost_cents>=0), discount_cents INTEGER NOT NULL CHECK(discount_cents>=0), status TEXT NOT NULL DEFAULT 'completed', date TEXT NOT NULL, user_id TEXT NOT NULL REFERENCES users(id), created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS sale_items (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL REFERENCES tenants(id), sale_id TEXT NOT NULL REFERENCES sales(id), product_id TEXT NOT NULL REFERENCES products(id), name TEXT NOT NULL, quantity REAL NOT NULL CHECK(quantity>0), price_cents INTEGER NOT NULL, vat_rate INTEGER NOT NULL, cost_cents INTEGER);
CREATE TABLE IF NOT EXISTS expenses (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL REFERENCES tenants(id), branch_id TEXT NOT NULL REFERENCES branches(id), name TEXT NOT NULL, category TEXT NOT NULL, kind TEXT NOT NULL, amount_cents INTEGER NOT NULL CHECK(amount_cents>0), net_cents INTEGER NOT NULL CHECK(net_cents>0), vat_rate INTEGER NOT NULL, date TEXT NOT NULL, due_date TEXT, status TEXT NOT NULL, account_id TEXT REFERENCES accounts(id), supplier_id TEXT, note TEXT NOT NULL DEFAULT '', created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS ledger (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL REFERENCES tenants(id), branch_id TEXT NOT NULL REFERENCES branches(id), account_id TEXT NOT NULL REFERENCES accounts(id), amount_cents INTEGER NOT NULL, kind TEXT NOT NULL, ref_id TEXT, note TEXT NOT NULL DEFAULT '', date TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS entities (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL REFERENCES tenants(id), branch_id TEXT REFERENCES branches(id), kind TEXT NOT NULL, name TEXT NOT NULL, data TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS documents (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL REFERENCES tenants(id), branch_id TEXT NOT NULL REFERENCES branches(id), name TEXT NOT NULL, mime TEXT NOT NULL, size INTEGER NOT NULL, record_id TEXT, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS audit_logs (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL REFERENCES tenants(id), user_id TEXT NOT NULL, user_name TEXT NOT NULL, branch_id TEXT, action TEXT NOT NULL, description TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS commands (tenant_id TEXT NOT NULL, id TEXT NOT NULL, body_hash TEXT NOT NULL, result TEXT NOT NULL, PRIMARY KEY(tenant_id,id));
CREATE INDEX IF NOT EXISTS idx_branches_tenant ON branches(tenant_id);
CREATE INDEX IF NOT EXISTS idx_users_tenant ON users(tenant_id);
CREATE INDEX IF NOT EXISTS idx_products_tenant ON products(tenant_id);
CREATE INDEX IF NOT EXISTS idx_materials_tenant ON materials(tenant_id);
CREATE INDEX IF NOT EXISTS idx_recipes_tenant ON recipes(tenant_id);
CREATE INDEX IF NOT EXISTS idx_inventory_scope ON inventory(tenant_id,branch_id);
CREATE INDEX IF NOT EXISTS idx_moves_scope ON moves(tenant_id,branch_id,date);
CREATE INDEX IF NOT EXISTS idx_sales_scope ON sales(tenant_id,branch_id,date);
CREATE INDEX IF NOT EXISTS idx_saleitems_scope ON sale_items(tenant_id,sale_id);
CREATE INDEX IF NOT EXISTS idx_expenses_scope ON expenses(tenant_id,branch_id,date);
CREATE INDEX IF NOT EXISTS idx_accounts_scope ON accounts(tenant_id,branch_id);
CREATE INDEX IF NOT EXISTS idx_ledger_scope ON ledger(tenant_id,branch_id,date);
CREATE INDEX IF NOT EXISTS idx_entities_scope ON entities(tenant_id,kind,branch_id);
CREATE INDEX IF NOT EXISTS idx_documents_scope ON documents(tenant_id,branch_id);
CREATE INDEX IF NOT EXISTS idx_audit_scope ON audit_logs(tenant_id,created_at);
CREATE TRIGGER IF NOT EXISTS ledger_no_delete BEFORE DELETE ON ledger BEGIN SELECT RAISE(ABORT,'Ledger is immutable'); END;
CREATE TRIGGER IF NOT EXISTS ledger_no_update BEFORE UPDATE ON ledger BEGIN SELECT RAISE(ABORT,'Ledger is immutable'); END;
CREATE TRIGGER IF NOT EXISTS audit_no_delete BEFORE DELETE ON audit_logs BEGIN SELECT RAISE(ABORT,'Audit is immutable'); END;
CREATE TRIGGER IF NOT EXISTS audit_no_update BEFORE UPDATE ON audit_logs BEGIN SELECT RAISE(ABORT,'Audit is immutable'); END;
CREATE TRIGGER IF NOT EXISTS sales_no_delete BEFORE DELETE ON sales BEGIN SELECT RAISE(ABORT,'Use reversal'); END;
CREATE TRIGGER IF NOT EXISTS expenses_no_delete BEFORE DELETE ON expenses BEGIN SELECT RAISE(ABORT,'Use reversal'); END;
